version: '3'
services:
#  rabbitmq:
#    image: rabbitmq:3-management
#    hostname: rabbit
#    ports:
#    - 15672:15672
#    - 5672:5672
#    labels:
#      NAME: rabbitmq
#    volumes:
#    - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
  consul-agent:
    image: consul:latest
    hostname: consul
    ports:
    - 8300:8300
    - 8400:8400
    - 8500:8500
    - 8600:8600